"""
Initial database schema for Kiapat.  This Alembic revision creates all
tables defined in the SQLAlchemy models.
"""

from alembic import op
import sqlalchemy as sa

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('admin', 'driver', name='roleenum'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('email')
    )
    op.create_table('classifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='sizeenum'), nullable=False),
        sa.Column('color', sa.Enum('WHITE', 'BROWN', name='colorenum'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('size', 'color', name='uq_classifications_size_color')
    )
    op.create_table('prices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('classification_id', sa.Integer(), nullable=False),
        sa.Column('unit', sa.Enum('TRAY', 'DOZEN', 'PCS', name='unitenum'), nullable=False),
        sa.Column('price_per_unit', sa.Float(), nullable=False),
        sa.Column('effective_from', sa.DateTime(), nullable=False),
        sa.Column('effective_to', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_balances',
        sa.Column('classification_id', sa.Integer(), nullable=False),
        sa.Column('qty_pcs', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
        sa.PrimaryKeyConstraint('classification_id')
    )
    op.create_table('invoices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_name', sa.String(), nullable=True),
        sa.Column('customer_phone', sa.String(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=False),
        sa.Column('signature_png_path', sa.String(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('IN', 'OUT', name='movementtype'), nullable=False),
        sa.Column('classification_id', sa.Integer(), nullable=False),
        sa.Column('qty_pcs', sa.Integer(), nullable=False),
        sa.Column('unit_entered', sa.Enum('TRAY', 'DOZEN', 'PCS', name='unitenum'), nullable=False),
        sa.Column('qty_entered', sa.Integer(), nullable=False),
        sa.Column('by_user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('DRAFT', 'VERIFIED', 'COMMITTED', name='movementstatus'), nullable=False),
        sa.Column('linked_invoice_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('committed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
        sa.ForeignKeyConstraint(['linked_invoice_id'], ['invoices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('classification_id', sa.Integer(), nullable=False),
        sa.Column('unit', sa.Enum('TRAY', 'DOZEN', 'PCS', name='unitenum'), nullable=False),
        sa.Column('qty', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('line_total', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('inventory_movements')
    op.drop_table('invoices')
    op.drop_table('inventory_balances')
    op.drop_table('prices')
    op.drop_table('classifications')
    op.drop_table('users')
    # ### end Alembic commands ###